### ISSUE TITLE
Not able to log in with HTTPS

### ISSUE THREAD

**Issue by tjhackzy** [siteinspector/siteinspector#25]
Hi. 

It runs perfectly fine on http but when I configured it with reverse proxy nginx and running it with custom port with https:// , I can no longer log in. 

Site loads and log in screen appears but on trying to log in I get " The change you wanted was rejected.
Maybe you tried to change something you didn't have access to.

If you are the application owner check the logs for more information." 

On checking logs,  I am getting : 

18:30:17 web.1    | I, [2022-02-15T18:30:17.300439 #10]  INFO -- : [9f2ddd0d-8220-4f51-bbc6-c13572621da0] {"method":"POST","path":"/sign_in","format":"html","controller":"Devise::SessionsController","action":"create","status":422,"error":"ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken","duration":840.81,"view":0.0,"db":0.0,"fwd":"------","referrer":"https://siteinspector.jayvardhan.online:809/sign_in","ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36","uid":2},
18:31:48 web.1    | I, [2022-02-15T18:31:48.207479 #10]  INFO -- : [42e91208-3ef3-4830-9058-0cfa3574e120] {"method":"GET","path":"/sign_in","format":"html","controller":"Devise::SessionsController","action":"new","status":200,"duration":7.65,"view":3.49,"db":0.61,"fwd":"-------------","referrer":null,"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36","uid":null},
18:32:11 web.1    | I, [2022-02-15T18:32:11.112482 #10]  INFO -- : [8b5402de-618b-4b6c-b5b3-152eb7262d17] {"method":"GET","path":"/sign_in","format":"html","controller":"Devise::SessionsController","action":"new","status":200,"duration":12.4,"view":5.42,"db":0.99,"fwd":"------","referrer":null,"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0","uid":null},
18:32:29 web.1    | W, [2022-02-15T18:32:29.451420 #10]  WARN -- : [cff08f55-e519-4b7a-b485-3c909e9dfed3] HTTP Origin header (https://siteinspector.jayvardhan.online:809) didn't match request.base_url (https://siteinspector.jayvardhan.online),
18:32:30 web.1    | I, [2022-02-15T18:32:30.222359 #10]  INFO -- : [cff08f55-e519-4b7a-b485-3c909e9dfed3] {"method":"POST","path":"/sign_in","format":"html","controller":"Devise::SessionsController","action":"create","status":422,"error":"ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken","duration":773.47,"view":0.0,"db":0.0,"fwd":"--------------","referrer":"https://siteinspector.jayvardhan.online:809/sign_in","ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0","uid":2}

my Nginx configuration is working fine and it loads fine. I got above error only with HTTPS. If I run with HTTP, it runs and logs in fine.

**Comment by omohokcoj** [comment]
@tjhackzy can you provide your nginx config?

**Comment by tjhackzy** [comment]
Hi @omohokcoj 

Sure. 

I have service running at localhost:808 perfectly fine. 
After adding it as reverse proxy on port 809, site loads perfectly but when I try to log in,
it shows above error. 

I have fired up my server : https://siteinspector.jayvardhan.online:809/sign_in
In case you want to try it your self.

Here's my configuration. 
-------------
server {
    listen  809 ssl;
    server_name _;

    ssl_certificate     /home/tjhackz/myssl/jayvardhan.online/fullchain1.pem;
    ssl_certificate_key /home/tjhackz/myssl/jayvardhan.online/privkey1.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    large_client_header_buffers 4 64k;
    location / {
        proxy_pass         http://localhost:808;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}

**Comment by omohokcoj** [comment]
@tjhackzy try to remove `proxy_set_header   Host $host;` line - it should fix the issue

**Comment by tjhackzy** [comment]
Hi again @omohokcoj 

I did as per your above suggestion and started/reloaded everything but looks like I am still facing the same issue. 

Here's the logs:

09:35:37 web.1    | W, [2022-02-16T09:35:37.742306 #9]  WARN -- : [bc5374b0-120f-4970-ac69-fd4c5a1f7276] HTTP Origin header (https://siteinspector.jayvardhan.online:809) didn't match request.base_url (https://localhost:808),
09:35:38 web.1    | I, [2022-02-16T09:35:38.198934 #9]  INFO -- : [bc5374b0-120f-4970-ac69-fd4c5a1f7276] {"method":"POST","path":"/sign_in","format":"html","controller":"Devise::SessionsController","action":"create","status":422,"error":"ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken","duration":457.99,"view":0.0,"db":0.0,"fwd":"------------","referrer":"https://siteinspector.jayvardhan.online:809/sign_in","ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36","uid":2},
09:35:38 web.1    | F, [2022-02-16T09:35:38.200635 #9] FATAL -- : [bc5374b0-120f-4970-ac69-fd4c5a1f7276]   ,
09:35:38 web.1    | [bc5374b0-120f-4970-ac69-fd4c5a1f7276] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):




To me, it looks more like some other issue but nginx reverse proxy as when I try to use the same without reverse proxy and with my https://InternallocalIP:MyInternalPort , it still shows me the same error.

**Comment by omohokcoj** [comment]
@tjhackzy oh i think i figured this out - so your nginx setup was correct - the problem is that site inspector doesn't support https on 809 port - so in order to make it work you need to host it on a regular 443 https port - for now thats the only option.

**Comment by tjhackzy** [comment]
@omohokcoj 

Oh snap! That's what I was worrying. My isp has blocked popular ports like 80, 8080, 443 and 22. So, in order to use https and some other services, I have to use some random ports with https. 

Do you have any suggestion by which I could use your application with custom https ports? I mean I can fork and may be able to do some adjustments into the code. (if needed).

**Comment by omohokcoj** [comment]
@tjhackzy try `proxy_set_header   Host siteinspector.jayvardhan.online;`
Basically you need to configure nginx so it sends 'Host: siteinspector.jayvardhan.online' header (without 803 port) to site inspector server.

**Comment by tjhackzy** [comment]
Hi again @omohokcoj 

I have set the proxy header Host with above one but still getting this : 


11:49:05 web.1    | W, [2022-02-16T11:49:05.603622 #9]  WARN -- : [c03a7a1e-0549-45a5-9459-e30f6152bdf6] HTTP Origin header (https://siteinspector.jayvardhan.online:809) didn't match request.base_url (https://siteinspector.jayvardhan.online)


And I think you're 100% right with the nginx sending the exact same host name instead of the one without port number with it. 

:(

**Comment by tjhackzy** [comment]
Right. I am closing this issue.
